apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuralseek-db
  namespace: neuralseek
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neuralseek-db
  template:
    metadata:
      labels:
        app: neuralseek-db
    spec:
      volumes:
      - name: neuralseek-config-vol
        configMap:
          name: neuralseek-config
      imagePullSecrets:
      - name: docker-cred-secret
      containers:
      - name: db
        image: 10.65.159.186:5000/neuralseek/neuralseek-db:latest
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: "RuntimeDefault"
        ports:
        - containerPort: 7687
        - containerPort: 6373